package id.ac.poliban.mi.listmakanan;

import java.util.ArrayList;
import java.util.List;

public class MakananData {
    static List<Makanan> getAllMakanans(){
        List<Makanan> data = new ArrayList<>();
        {
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Sop_Banjar_Sate_Banjar.JPG/240px-Sop_Banjar_Sate_Banjar.JPG", "Soto Banjar", "Soto Banjar adalah soto khas suku Banjar, Kalimantan Selatan dengan bahan utama ayam serta memiliki aroma harum rempah-rempah seperti kayu manis, biji pala, dan cengkih. Ada kalanya pembuatan kuah soto banjar dapat dicampurkan dengan sedikit susu yang membuat warna kuahnya mejadi tidak bening, tetapi sedikit keruh. Soto ini berisi daging ayam yang sudah disuwir-suwir, dengan tambahan perkedel, kentang rebus, rebusan telur, potongan wortel dan ketupat.[1]\n" +
                    "\n" +
                    "Seperti halnya soto ayam, bumbu soto Banjar berupa bawang merah, bawang putih dan merica, tetapi tidak memakai kunyit. Bumbu ditumis lebih dulu dengan sedikit minyak goreng atau minyak samin hingga harum sebelum dimasukkan ke dalam kuah rebusan ayam. Rempah-rempah nantinya diangkat agar tidak ikut masuk ke dalam mangkuk sewaktu dihidangkan.\n" +
                    "\n" +
                    "Penjual soto Banjar biasanyan juga menyajikan sate ayam sebagai menu pendamping. Nasi sop adalah sebutan untuk soto Banjar yang dikuahkan ke sepiring nasi."));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Kue_bika_ambon.JPG/220px-Kue_bika_ambon.JPG", "Bika Ambon", "Bika ambon adalah sejenis penganan asal Indonesia. Terbuat dari bahan-bahan seperti telur, gula, dan santan, bika ambon umumnya dijual dengan rasa pandan, meskipun kini juga tersedia rasa-rasa lainnya seperti durian, keju, dan cokelat. Bika ambon biasanya dapat bertahan dalam kondisi terbaik selama sekitar empat hari karena setelah itu kue tersebut mulai mengeras.\n" +
                    "\n" +
                    "Menurut penjelasan M Muhar Omtatok, seorang budayawan dan sejarawan, kue bika ambon terilhami dari kue khas Melayu yaitu Bika atau Bingka. Selanjutnya dimodifikasi dengan bahan pengembang berupa nira/tuak enau hingga berongga dan berbeda dari kue Bika atau Bingka khas Melayu itu. Selanjutnya M Muhar Omtatok menyebutkan bahwa kue ini disebut bika ambon karena pertama sekali dijual dan popular di simpang Jl Ambon-Sei Kera Medan. "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Mie_Aceh_with_beef.jpg/250px-Mie_Aceh_with_beef.jpg", "Mi Aceh", "Mie Aceh adalah masakan mie pedas khas Aceh di Indonesia. Mie kuning tebal dengan irisan daging sapi, daging kambing atau makanan laut (udang dan cumi) disajikan dalam sup sejenis kari yang gurih dan pedas. Mie Aceh tersedia dalam tiga jenis, Mie Aceh Goreng (digoreng dan kering), Mie Aceh Tumis (dengan sedikit kuah) dan Mie Aceh Kuah (sup). Biasanya ditaburi bawang goreng dan disajikan bersama emping, potongan bawang merah, mentimun, dan jeruk nipis."));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Rendang_daging_sapi_asli_Padang.JPG/250px-Rendang_daging_sapi_asli_Padang.JPG", "Rendang", "Rendang atau randang (Jawi: رندڠ) adalah masakan daging dengan bumbu rempah-rempah yang berasal dari Minangkabau. Masakan ini dihasilkan dari proses memasak yang dipanaskan berulang-ulang menggunakan santan sampai kuahnya kering sama sekali. Proses memasaknya memakan waktu berjam-jam (biasanya sekitar empat jam) hingga yang tinggal hanyalah potongan daging berwarna hitam pekat. Dalam suhu ruangan, rendang dapat bertahan hingga berminggu-minggu. Rendang yang dimasak dalam waktu yang lebih singkat dan santannya belum mengering disebut kalio, berwarna cokelat terang keemasan.\n" +
                    "\n" +
                    "Rendang dapat dijumpai di Rumah Makan Padang di seluruh dunia. Masakan ini populer di Indonesia dan negara-negara Asia Tenggara lainnya, seperti Malaysia, Singapura, Brunei, Filipina dan Thailand. Di daerah asalnya, Minangkabau, rendang disajikan di berbagai upacara adat dan perhelatan istimewa. Meskipun rendang merupakan masakan tradisional Minangkabau, teknik memasak serta pilihan dan penggunaan bumbu rendang berbeda-berda menurut daerah. "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Otak-otak.jpg/250px-Otak-otak.jpg", "Otak-otak", "Otak-otak adalah makanan yang terbuat dari daging tenggiri cincang yang dibungkus dengan daun pisang, dipanggang, dan disajikan dengan kuah asam pedas. Penganan ini populer di kawasan sekitar Selat Malaka dan Selat Karimata, seperti Kepulauan Riau, Singapura, dan Malaysia, tetapi tersebar luas pula di berbagai kota di Sumatra dan Jawa. Di Malaysia, Muar terkenal dengan otak-otaknya. Di Indonesia sendiri otak-otak banyak dijumpai di Tanjungpinang dan Palembang. "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Pempekraden_kapal_selam_dan_kulit_ikan.jpg/250px-Pempekraden_kapal_selam_dan_kulit_ikan.jpg", "Pempek", "Pempek atau empek-empek adalah makanan khas Palembang yang terbuat dari daging ikan yang digiling lembut dan tepung kanji (secara salah kaprah sering disebut sebagai \"tepung sagu\"), serta beberapa komposisi lain seperti telur, bawang putih yang dihaluskan, penyedap rasa dan garam. Sebenarnya sulit untuk mengatakan bahwa penganan pempek pusatnya adalah di Palembang karena hampir semua daerah di Sumatera Selatan memproduksinya.\n" +
                    "\n" +
                    "Pempek bisa ditemukan dengan sangat mudah di seantero Kota Palembang; ada yang menjual di restoran, ada yang di pinggir jalan, dan juga ada yang dipikul. Tahun 1980-an, penjual biasa memikul satu keranjang penuh pempek sambil berjalan kaki berkeliling menjajakan makanannya. "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/id/thumb/a/ae/Bakmi_bangka.jpg/220px-Bakmi_bangka.jpg", "Mi Bangka", "Mie Bangka atau dikenal sebagai Bakmi Bangka adalah salah satu dari sekian banyak ciri khas kuliner masyarakat pulau Bangka. Masakan ini lebih dikenal sebagai Mien di pulau asalnya dan merupakan jenis masakan Khek / Hakka. Kelezatan, dan kemudahan penyajiannya membuat masakan ini sangat populer sehingga tersebar di banyak kota Indonesia."));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Serabi-01.jpg/250px-Serabi-01.jpg", "Serabi", "Serabi (bahasa Jawa: ꦱꦿꦧꦶ, Aksara Sunda Baku: ᮞᮧᮛᮘᮤ) (Sd. sorabi, surabi; Jw. srabi) merupakan jajanan pasar tradisional yang berasal dari Indonesia. Ada dua jenis serabi, yaitu serabi manis yang menggunakan kinca (gula merah cair) dan serabi asin dengan atau tanpa taburan oncom yang telah dibumbui di atasnya. Di Bandung, serabi biasa dijajakan di pagi hari dan dimasak menggunakan tungku sehingga menghasilkan rasa yang khas. Kadangkala telur ayam yang telah dikocok ditambahkan ke atas adonan serabi yang sedang dimasak. Seiring dengan perkembangan zaman, banyak yang terus berinovasi dengan menambahkan berbagai topping seperti sosis, keju, maupun mayones yang tujuannya untuk mematahkan asumsi bahwa serabi adalah makanan yang terkesan rendahan. Tempat yang menyajikan serabi dengan berbagai variasi rasa tersebar di kota-kota besar seperti Jakarta, Bandung, dan Bogor. "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Rujakcingur.jpg/250px-Rujakcingur.jpg", "Rujak Cingur", "Rujak cingur adalah salah satu makanan tradisional yang mudah ditemukan di daerah Jawa Timur, terutama daerah asalnya Surabaya. Dalam bahasa Jawa kata cingur berarti \"mulut\", hal ini merujuk pada bahan irisan mulut atau moncong sapi yang direbus dan dicampurkan ke dalam hidangan. Rujak cingur biasanya terdiri dari irisan beberapa jenis buah seperti timun, kerahi (krai, yaitu sejenis timun khas Jawa Timur), bengkuang, mangga muda, nanas, kedondong, kemudian ditambah lontong, tahu, tempe, bendoyo, cingur, serta sayuran seperti kecambah/taoge, kangkung, dan kacang panjang. Semua bahan tadi dicampur dengan saus atau bumbu yang terbuat dari olahan petis udang, air matang untuk sedikit mengencerkan, gula/gula merah, cabai, kacang tanah yang digoreng, bawang goreng, garam, dan irisan tipis pisang biji hijau yang masih muda (pisang klutuk). Semua saus/bumbu dicampur dengan cara diulek, itu sebabnya rujak cingur juga sering disebut rujak ulek."));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/id/thumb/2/2f/Ayam-cincane.jpg/220px-Ayam-cincane.jpg", "Ayam Cincane", "Ayam cincane adalah masakan khas Kalimantan Timur[1]. Hidangan ini sering dijumpai pada acara-acara besar, seperti pesta pernikahan dan acara penyambutan tamu-tamu kehormatan. Selain itu, masakan ini juga dapat dijumpai di beberapa kedai ataupun rumah makan. Daging ayam kampung yang disajikan bersama bumbu berwarna kemerahan menjadi ciri khas tersendiri dari menu ayam cincane[2]."));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Papeda%2C_Kuah_Kuning%2C_Ikan_Tude_Bakar_2.jpg/260px-Papeda%2C_Kuah_Kuning%2C_Ikan_Tude_Bakar_2.jpg", "Papeda", "Papeda adalah makanan berupa bubur sagu khas Maluku dan Papua yang biasanya disajikan dengan ikan tongkol atau mubara yang dibumbui dengan kunyit.[1] Papeda berwarna putih dan bertekstur lengket menyerupai lem dengan rasa yang tawar.[1] Papeda merupakan makanan yang kaya serat, rendah kolesterol dan cukup bernutrisi.[2] "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Sate_Ponorogo.jpg/220px-Sate_Ponorogo.jpg", "Sate", "Sate (ejaan KBBI: satai) adalah makanan yang terbuat dari daging yang dipotong kecil-kecil dan ditusuk sedemikian rupa dengan tusukan lidi tulang daun kelapa atau bambu kemudian dipanggang menggunakan bara arang kayu. Sate disajikan dengan berbagai macam bumbu yang bergantung pada variasi resep sate.[1] Daging yang dijadikan sate antara lain daging ayam, kambing, domba, sapi, babi, kelinci, kuda, dan lain-lain.\n" +
                    "\n" +
                    "Sate diketahui berasal dari Jawa, Indonesia, dan dapat ditemukan di mana saja di Indonesia dan telah dianggap sebagai salah satu masakan nasional Indonesia.[2] Sate juga populer di negara-negara Asia Tenggara lainnya seperti Malaysia, Singapura, Filipina, dan Thailand. Sate juga populer di Belanda yang dipengaruhi masakan Indonesia yang dulu merupakan koloninya. "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Sop_Konro.JPG/250px-Sop_Konro.JPG", "Sup Konro", "Sup Konro adalah masakan sup iga sapi khas Indonesia yang berasal dari tradisi Bugis dan Makassar.[1] Sup ini biasanya dibuat dengan bahan iga sapi atau daging sapi.[1][2] Masakan berkuah warna coklat kehitaman ini biasa dimakan dengan burasa dan ketupat yang dipotong-potong terlebih dahulu. Warna gelap ini berasal dari buah kluwek yang memang berwarna hitam. Bumbunya relatif \"kuat\" akibat digunakannya ketumbar. Rasa pedas dan berbumbu ini dibuat dari campuran rempah-rempah, seperti ketumbar, keluwak (buah yang menyebabkan masakan berwarna hitam), sedikit pala, kunyit, kencur, kayu manis, asam, daun lemon, cengkih, dan daun salam.[3] "));
            data.add(new Makanan("https://upload.wikimedia.org/wikipedia/id/thumb/c/c4/Ayam-Betutu-%E2%80%93-Bali.jpg/220px-Ayam-Betutu-%E2%80%93-Bali.jpg", "Ayam Betutu", "Betutu adalah lauk yang terbuat dari ayam atau bebek yang utuh yang berisi bumbu, kemudian dipanggang dalam api sekam. Betutu ini telah dikenal di seluruh kabupaten di Bali. Salah satu produsen betutu adalah desa Melinggih, kecamatam payangan kabupaten Gianyar. Ayam betutu juga merupakan makanan khas Gilimanuk. Betutu digunakan sebagai sajian pada upacara keagamaan dan upacara adat serta sebagai hidangan dan di jual. Konsumennya tidak hanya masyarakat Bali tetapi juga tamu manca negara yang datang ke Bali, khususnya pada tempat-tempat tertentu seperti di hotel dan rumah makan atau restoran. Betutu tidak tahan disimpan lama.Be-Tutu merupakan jenis makanan tradisional daerah Bali yang bahan mentahnya berupa karkas utuh itik dan ayam."));
        }

        return data;

    }
}
